name: 仓库保活
on:
  schedule:
    - cron: '0 0 15 * *'  #每月15号执行一次
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_KEEPALIVE_TOKEN }}

      - name: Empty commit keep‑alive
        run: |
          git config --global user.name "KeepAliveBot"
          git config --global user.email "bot@example.com"
          git commit --allow-empty -m "chore: keep alive"
          git push
